### ISSUE TITLE
Is it a good idea to get rid of the "Purpose" multiple choice question at the beginning of the survey?

### ISSUE THREAD

**Issue by danelimjoco** [AguaClara/post.odkForms#8]
I was thinking it is probably a good idea to get rid of the "Purpose" multiple choice question at the beginning of the survey because @jacuerp explained that it is sort of dated and only because plant operators got used to hitting the first option were the additional questions added to the end asking if operators want to submit backwash data, pH data, and other stuff. So I think because operators are already used to hitting the first option, maybe just get rid of the other options entirely and throw the additional questions at the end no matter what, depending on whether or not the questions are applicable for a particular plant. This could be good for us because 1) we don't need to ask if operators want to submit other data if that plant doesn't even need to submit those other things, 2) operators will likely just get used to going through the entire form and when they come across questions like backwash and its not applicable at the time, they'll just know when to skip it or input data, rather than not putting in data if they're supposed to. 

What do you think about this @ethan92429?

**Comment by ethan92429** [comment]
@danelimjoco I like your thinking - we certainly want to pare down the form as much as possible, but I'm worried about what will happen to questions about things that happen very infrequently, such as changing the stock tank concentration and reporting maintenance. We added backwash as an additional question at the end because that happens so often - particularly in a plant with 4 filters! But a new stock concentration isn't as common, and if we add it to the end, we are back to the problem of over-loading the forms with too many questions - the reason you proposed this option in the first place. Therefore I'm in favor of leaving the 'purpose' field so as to give the operators an option to jump straight to reporting specifically what they need to report instead of slogging through so many screens. @danelimjoco and @jacuerp does that make sense?

**Comment by ethan92429** [comment]
We will leave the purpose field because there is not enough motivation to get rid of it.
